account/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    RegisterCreateView,
    RegisterDoneView,
    DonateView,
    # DonationUserDetailView,
    payment_process,
    anonym_payment_process,
)

app_name = 'account'

urlpatterns = [
    path("register/", RegisterCreateView.as_view(), name="register"),
    path("congratulation/", RegisterDoneView.as_view(), name="register_done"),
    path("donate/", DonateView.as_view(), name='donate'),
    path('profile/<str:membership_id>56443323454555/', payment_process, name='profile'),
    path('pay-anonym/',  anonym_payment_process, name='anonym'),
]

core/urls.py
from django.urls import path

from .views import (
    HomePageView
)

app_name = 'core'


urlpatterns = [
    path("", HomePageView.as_view(), name="index")
]

ffa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('account/', include('account.urls', namespace='account')),
]

account/models.py
import uuid
from django.conf import settings
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from core.models import Subscriber
from .managers import UserManager


class DonationUser(models.Model):
    full_name = models.CharField(_('full name'), max_length=80, blank=True)
    membership_id = models.CharField(_("Membership id"), max_length=1000000, default='', null=True, blank=True)
    email = models.EmailField(_('email address'), unique=True, blank=True)
    birthday = models.DateField(_("Birthday"), auto_now_add=False, auto_now=False, blank=True)
    phone_number = models.CharField(_('phone number'), max_length=30, blank=True)
    citizenship = models.CharField(_('citizenship'), max_length=225, blank=True)
    education = models.CharField(_('education'), max_length=225, blank=True)
    current = models.CharField(_('current'), max_length=225, blank=True)
    permoment = models.CharField(_('permoment'), max_length=225)
    member_of_ngo = models.CharField(_('member of ngo'), max_length=225, blank=True)
    usa_year = models.IntegerField(_('usa year'), null=True)
    reasons = models.TextField(_('reasons'), blank=True)
    mention = models.TextField(_('mention'), blank=True)


    #moderations
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(_("Active"), default=False)


    class Meta:
        """Meta definition for Contact."""
        verbose_name = 'Member'
        verbose_name_plural = 'Members'
        ordering = ('-id',)

    def save(self, *args, **kwargs):
        super(DonationUser, self).save(*args, **kwargs)
        raw_id = uuid.uuid1()
        raw_membership_id = str(raw_id.int)[:6]
        self.membership_id = f'{raw_membership_id}{self.id}'
        if self.is_active == True:
            send_mail('subject', f'This is you membership id {self.membership_id}', 'husubayli@gmail.com', [self.email,])
        else:
            send_mail('subject', f'Your form on review', 'husubayli@gmail.com', [self.email,])
        super(DonationUser, self).save(*args, **kwargs)

    USERNAME_FIELD = ['membership_id']

    objects = UserManager()

    def __str__(self):
        created_date = self.created_at.date()
        return  f'{self.email}'
            
    
    def get_absolute_url(self):
        return reverse_lazy("account:profile", kwargs={"membership_id": self.membership_id})
    

class Message(models.Model):
    subject = models.CharField(_('Subject'), max_length=80, blank=True)
    content = models.TextField(_('Content'), blank=True)

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.subject

    def save(self, *args, **kwargs):
        subscribers = [i for i in Subscriber.objects.all()]
        print(subscribers)
        for subscriber in subscribers:
            send_mail(self.subject, self.content, 'husubayli@gmail.com', [subscriber.mail])
        super(Message, self).save(*args, **kwargs)

account/forms.py
from django import forms
from django.forms import widgets
from .models import DonationUser


from django.contrib.auth.forms import UserCreationForm


class RegisterForm(forms.ModelForm):

    class Meta:
        model = DonationUser
        fields = (
            "full_name", 
            "email","birthday", 
            "phone_number", 
            "citizenship", 
            "education", 
            "current", 
            "permoment", 
            "member_of_ngo", 
            "usa_year", 
            "reasons", 
            "mention"
        )

        widgets = {
            'full_name': forms.TextInput(
                attrs={
                    'name': 'fname',
                    'class': 'form-elements',
                    'placeholder': 'Name and Surname'
                }
            ),
            'birthday': forms.DateInput(
                attrs={
                    'id': 'date',
                    'name': 'dd',
                    'type': 'date',
                    'class': 'form-elements',
                    'placeholder': 'Date of Birth',
                    'onfocus': "(this.type='date')",
                    'onblur': "(this.type='text')",
                    'oninput': "this.className = ''"
                    
                }
            ),
            'email':  forms.EmailInput(
                attrs={
                    'name': 'email',
                    'class': 'form-elements',
                    'placeholder': 'E-mail address'
                }
            ),
            'phone_number' : forms.TextInput(
                attrs={
                    'name': 'phone',
                    'placeholder': 'Phone Number',
                    'class': 'form-elements', 
                    }
            ),
            'citizenship': forms.TextInput(
                attrs={
                    'name': 'citizen',
                    'class': 'form-elements',
                    'placeholder': 'Citizenship'
                }
            ),
            'education': forms.TextInput(
                attrs={
                    'name': 'edu',
                    'class': 'form-elements',
                    'placeholder': 'Education'
                }
            ),
            'current': forms.TextInput(
                attrs={
                    'name': 'employe',
                    'class': 'form-elements',
                    'placeholder': 'Current employer and Position'
                }
            ),
            'permoment': forms.TextInput(
                attrs={
                    'name': 'permoment',
                    'class': 'form-elements',
                    'placeholder': 'Permament/Mailing adress'
                }
            ),
            'member_of_ngo': forms.TextInput(
                attrs={
                    'name': 'member',
                    'class': 'form-elements',
                    'placeholder': 'Member of other NGOs or Associations'
                }
            ),
            'member_of_ngo': forms.TextInput(
                attrs={
                    'name': 'member',
                    "cols": "63",
                    "rows": "7",
                    'class': 'form-elements',
                    'placeholder': 'Member of other NGOs or Associations'
                }
            ),
            'usa_year': forms.NumberInput(
                attrs={
                    'name': 'year',
                    'class': 'form-elements',
                    'placeholder': 'The year move to USA'
                }
            ),
            'reasons': forms.Textarea(
                attrs={
                    'name': '',
                    "cols": "63",
                    "rows": "7",
                    'class': 'form-elements',
                    'placeholder': 'Please mention the reasons why you wish to join FAA and your expectation from organization'
                }
            ),
            'mention': forms.Textarea(
                attrs={
                    'name': '',
                    "cols": "63",
                    "rows": "7",
                    'class': 'form-elements',
                    'placeholder': 'Please mention the way you are willing to contribute with FAA'
                }
            ),

        }

class SignUpForm(forms.Form):
    membership_id = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-elements", 
                "placeholder": "ID",
                "name": "id",
                "id": "validationCustom03",
                'required': True
            },
    ),
)

account/views.py
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from paypal.standard.forms import PayPalPaymentsForm
from django.utils.html import format_html
from django.views.generic import (
    CreateView,
    TemplateView,
    DetailView,
)
from .models import DonationUser
from .forms import RegisterForm, SignUpForm


class RegisterCreateView(CreateView):
    model = DonationUser
    form_class = RegisterForm
    template_name = "registration.html"
    success_url = reverse_lazy('account:register_done')

    # def get_success_url(self):
    #     # print('here', reverse_lazy('account:register_done', kwargs={'pk': self.object.id}))
    #     return reverse_lazy('account:register_done', kwargs={'pk': self.object.id})


class RegisterDoneView(TemplateView):
    template_name = 'congratulation.html'


class DonateView(TemplateView):
    form_class = SignUpForm
    template_name = 'donate.html'

    def get(self, request):
        form = SignUpForm()

        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            # form.save()
            membership_id = request.POST.get('membership_id')
            user = DonationUser.objects.filter(
                membership_id=membership_id).first()
            if user is not None:
                if user.is_active:
                    return redirect(user.get_absolute_url())
            context = {'message': 'User with this membership id does not exsist', "form": form}
            return render(request, self.template_name, context)
        context = {'form': form}
        return render(request, self.template_name, context)


def payment_process(request, membership_id):
    user_object = DonationUser.objects.get(membership_id=membership_id)
    # amount = request.POST.get('amoun')
    paypal_dict = {
        "business": "faa.us.org@gmail.com",
        "amount": "",
        "item_name": "name of the item",
        "invoice": "unique-invoice-id",
        "notify_url": request.build_absolute_uri(reverse('core:index')),
        "return": request.build_absolute_uri(reverse('core:index')),
        "cancel_return": request.build_absolute_uri(reverse('core:index')),
        # Custom command to correlate to some function later (optional)
        "custom": "premium_plan",
    }
    # Create the instance.
    form = ExtPayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form, "user_object": user_object}
    return render(request, "profile.html", context)


class ExtPayPalPaymentsForm(PayPalPaymentsForm):
    def render(self):
        form_open = u'''<form action="%s" id="PayPalForm" method="post">''' % (
            self.get_endpoint())
        form_close = u'</form>'
        # format html as you need
        submit_elm = u'''<input type="submit" value="Donate" class="btn my-custom-class" id="simple" style="bacground-color: ;">'''
        return format_html(form_open+self.as_p()+submit_elm+form_close)


def anonym_payment_process(request):
    # user_object = DonationUser.objects.get(membership_id=membership_id)
    # amount = request.POST.get('amoun')
    paypal_dict = {
        "business": "faa.us.org@gmail.com",
        "amount": "",
        "item_name": "name of the item",
        "invoice": "unique-invoice-id",
        "notify_url": request.build_absolute_uri(reverse('core:index')),
        "return": request.build_absolute_uri(reverse('core:index')),
        "cancel_return": request.build_absolute_uri(reverse('core:index')),
        # Custom command to correlate to some function later (optional)
        "custom": "premium_plan",
    }
    # Create the instance.
    form = ExtPayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form}
    return render(request, "anonym.html", context)

account/templates/anonym.html
{% load static %}
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="America,Azerbaijan">
<meta name="description" content="The Federation of Azerbaijani Americans">
<title>The Federation of Azerbaijani Americans</title>
<link rel="icon" href="{% static 'images/logo.png' %}" type="image/gif" sizes="16x16">
<!-- Bootstrap css link -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!-- Google Fonts link -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet">

<!--Font awesome link  -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
    crossorigin="anonymous" />

<!-- Own css link -->
<link rel="stylesheet" href="{% static 'css/donate1.css' %}">

<style>
    #id_amount {
        display: block;
        border-radius: 4px;
        margin: auto;

    }
</style>

<body>
    <div class="container-fluid">
        <div class="row">
            
            <div class="right col-md-12">
                <img src="{% static 'images/logo.png' %}" alt="">

                <h1 id="section-header">Donate</h1>
                <p id="section-text">{{user_object.full_name}}</p>
                <form method="POST" class="needs-validation" id="payment-form">
                    {% csrf_token %}
                    <!-- <input type="submit"> -->
                </form>
                {{form.render}}
            </div>

        </div>
    </div>


    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
    <!--Bootstrap  JavaScript link-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/payment.js' %}"></script>

</body>

</html>

account/templates/congratulation.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="keywords" content="America,Azerbaijan">
  <meta name="description" content="The Federation of Azerbaijani Americans">
  <title> Federation of Azerbaijani Americans</title>
  <link rel="icon" href="{% static 'images/logo.png' %}" type="image/gif" sizes="16x16">
  <!-- Bootstrap css link -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <!-- Google Fonts link -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet">

  <!--Font awesome link  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
      integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
      crossorigin="anonymous" />
    
    <!-- Own Css -->
    <link rel="stylesheet" href="{% static 'css/congratulation.css' %}">
</head>
<body>
    <div class="container-fluid ">
<div class="row">
<div style="background-color: white;" class="left col-md-6 ">
      <img class="logo-img"   src="{% static 'images/logo.png' %}" alt="">
<h1 class="content-head"style="font-weight: 600; margin-bottom: 54px !important;" >Thank you!</h1>
<h6 class="content-head" style="font-size:28px!important;">Congratulations</h6>
<img  src="{% static 'images/clapping (3) 1.png' %}" alt="">
<br>
<button type="button" style="font-weight: 600;"  id="done" onclick=" relocate_home()"> Done </button>
<script>
  function relocate_home()
  {
      location.href = "{% url 'account:donate' %}";
  } 
  </script>
<p>Didn't receive an email? <a id="resend-link" href="{% url 'account:register_done' %}">Click to resend</a></p>
</div>  
<div  class="right col-md-6">
    <img style="width: 100%; height: 100%; "  src="{% static 'images/Mask Group (1).png' %}"  alt="">
    </div>
</div>
    </div>
    
  <!--Bootstrap  JavaScript link-->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
  integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
  crossorigin="anonymous"></script>
  <!-- Own Javascript link -->
  <script src="{% static 'js/register.js' %}"></script>


</body>
</html>

account/templates/donate.html
{% load static %}
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="keywords" content="America,Azerbaijan">
  <meta name="description" content="The Federation of Azerbaijani Americans">
  <title> Federation of Azerbaijani Americans</title>
  <link rel="icon" href="{% static 'images/logo.png' %}" type="image/gif" sizes="16x16">
<!-- Bootstrap css link -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
 integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!-- Google Fonts link -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet">

<!--Font awesome link  -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
 integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
 crossorigin="anonymous" />

 <!-- Own css link -->
 <link rel="stylesheet" href="{% static 'css/donate1.css' %}">
<body>
    <div class="container-fluid">
<div class="row">
  
<div class="right col-md-12">
    <img src="{% static 'images/logo.png' %}" alt="">

    <h1 id="section-header">Donate</h1>
    {% if message %}
      <p id="section-text" class="text-danger">{{ message }}</p>
    {% else %}
      <p id="section-text" style="font-size: 28px;">Please provide your membership ID</p>
    {% endif %}
    <form method="POST" class="needs-validation" novalidate id="don-form">
      {% csrf_token %}
      {{ form.none_field_errors }}
      <div class="form-row">
          <label for="validationCustom03"></label>
          <p>{{ form.membership_id }}</p>
          <p>{{ form.membership_id.errors }}</p>
          <!-- <input  class="form-control form-elements"  placeholder="ID" name="id" id="validationCustom03" required> -->
          {% if message %}
            <div class="invalid-feedback"> your email adress in invalid  </div>
          {% endif %}
      
        <br>
  
      <input type="submit" class="btn btn-primary" value="Donate" id="simple" onclick="donate_btn()">
    </form>
    <br>

      <!-- <button class="btn btn-primary" id="ananoymous" ><a href="{% url 'account:anonym' %}"></a>Donate as Anonymous</button> -->
      <a href="{% url 'account:anonym' %}" style="font-weight: 600;" class="btn btn-primary" id="ananoymous">Donate as Anonymous</a>

   
      <script>
        function donate_btn()
        {
            this.setAttribute('type', 'submit');
        } 
      </script>
      <script>
        function donate_ananoymous_btn()
        {
          this.setAttribute('type', 'submit');
        } 
      </script>
    
    <!-- <form id="regForm" class="g-3 needs-validation" novalidate action=""> -->
        <!-- One "tab" for each step in the form: -->
          <!-- <input required class="form-elements" placeholder="ID" id="user-id"  name="id"> -->
         <!-- 
            <button type="button" id="simple" >Donate</button><br>
          <button  class="btn" type="submit" style="margin-top: 1rem;" type="button" id="ananoymous">Donate as anonymous</button>
       
      </form> -->
      <br>
      <p>or</p>
      <br>
      <p > <b> <a id="became-member" href="{% url 'account:register' %}"> Became a member</a> </b> </p>
</div>

</div>
    </div>


    <script>
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
        'use strict';
        window.addEventListener('load', function() {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');
          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() === false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
      </script>
  <!--Bootstrap  JavaScript link-->
  <script>
    document.querySelector("#don-form").addEventListener('submit', function (e) {
      // e.preventDefault();
      document.querySelector("#validationCustom03").style.border = "1px solid  #b11b31"
    })
  </script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
  integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
  crossorigin="anonymous"></script>
  

</body>
</html>

account/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="America,Azerbaijan">
<meta name="description" content="The Federation of Azerbaijani Americans">
<title>The Federation of Azerbaijani Americans</title>
<link rel="icon" href="{% static 'images/logo.png' %}" type="image/gif" sizes="16x16">
<!-- Bootstrap css link -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!-- Google Fonts link -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet">

<!--Font awesome link  -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
    crossorigin="anonymous" />

<!-- Own css link -->
<link rel="stylesheet" href="{% static 'css/donate1.css' %}">
<style>
    #id_amount {
        display: block;
        border-radius: 4px;
        margin: auto;

    }
    /* .container-fluid {
        background-size: contain;
        background-repeat: no-repeat;
    } */
</style>
<body>
    <div class="container-fluid">
        <div class="row">
           
            <div class="right col-md-12">
                <img src="{% static 'images/logo.png' %}" alt="">

                <h1 id="section-header">Donate</h1>
                <p id="section-text">{{user_object.full_name}}</p>
                <form method="POST" class="needs-validation" id="payment-form">
                    {% csrf_token %}
                    <!-- <input type="submit"> -->
                </form>
                {{form.render}}
            </div>

        </div>
    </div>


    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
    <!--Bootstrap  JavaScript link-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/payment.js' %}"></script>

</body>

</html>